version: "3.4"

services:
  web:
    image: codeforacause/website-izadji:web-#{TAG_NUMBER}#
    container_name: website-izadji-web
    ports:
      - "28001:3002"
    environment:
      PORT: 3002
      REACT_APP_STRAPI_HOST: https://api.izadji.codeforacause.rs
    restart: unless-stopped
    depends_on:
      - api
  
  api:
    image: codeforacause/website-izadji:api-#{TAG_NUMBER}#
    container_name: website-izadji-api
    ports:
      - 28002:1337
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: #{APP_KEYS}#
      API_TOKEN_SALT: #{API_TOKEN_SALT}#
      ADMIN_JWT_SECRET: #{ADMIN_JWT_SECRET}#
      JWT_SECRET: #{JWT_SECRET}#
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_CONTACT_EMAIL: #{SMTP_CONTACT_EMAIL}#
      SMTP_CONTACT_PASSWORD: #{SMTP_CONTACT_PASSWORD}#
      SMTP_APPLICATION_EMAIL: #{SMTP_APPLICATION_EMAIL}#
      SMTP_APPLICATION_PASSWORD: #{SMTP_APPLICATION_PASSWORD}#
      IZADJI_URL: https://api.izadji.codeforacause.rs
      DATABASE_FILENAME: "../data.db/data.db"
    volumes:
      - "./data.db/:/data.db/:rw"
      - "./uploads:/app/public/uploads/:rw"
    restart: unless-stopped
