version: "3.4"

services:
  web:
    build:
      context: ./izadji/.
      dockerfile: Dockerfile.dev
    container_name: website-izadji-web
    ports:
      - "80:3002"
    environment:
      PORT: 3002
      REACT_APP_STRAPI_HOST: http://api:1337
    restart: unless-stopped
    depends_on:
      - api
  api:
    build:
      context: ./api/.
      dockerfile: Dockerfile.dev
    container_name: website-izadji-api
    ports:
      - "1337:1337"
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      IZADJI_URL: http://api:1337
      DATABASE_FILENAME: "../data.db/data.db"
    env_file:
      - ./api/.env
    volumes:
      - "./data.db/:/data.db/:rw"
      - "./uploads:/app/public/uploads/:rw"
    restart: unless-stopped
