name: deploy
on:
  push:
    branches:
      - main
      - feature/fix-deployment
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: npm install react-scripts
        working-directory: izadji
      - run: npm install
        working-directory: izadji
      - run: CI=false npm run build
        working-directory: izadji

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
          
      - name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo instal and deploy izadji website
            cd C:\Sites\website-izadji\
            echo moved to directory izadji
            git pull
            echo git pull
            cd C:\Sites\website-izadji\izadji
            nssm stop izadji-site
            npm ci
            npm install cross-env
            npm run build:win
            nssm start izadji-site
            echo npm run build done
            echo install and deploy strapi 
            cd C:\Sites\website-izadji\api
            echo moved to directory api
            nssm stop izadji-strapi
            yarn install
            yarn run build:win
            yarn run start:win
            nssm start izadji-strapi
            echo yarn run build done
